repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ['-S']
      name: black (python)
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      -   id: flake8
-   repo: https://github.com/pycqa/pylint
    rev: v4.0.0
    hooks:
      -   id: pylint
          name: pylint (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=512']
    - id: no-commit-to-branch # Prevents commits directly to master/main
      name: don't commit to default branch
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.0.5
  hooks:
      - id: sqlfluff-lint
        args: ['--dialect=postgres']
      - id: sqlfluff-fix
        args: ['--dialect=postgres']
